### ISSUE TITLE
Docs for deploying Cloud Foundry are stale

### ISSUE THREAD

**Issue by dsabeti** [cloudfoundry-incubator/bosh-google-cpi-release#158]
The docs [in this repo](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/tree/master/docs/cloudfoundry) for deploying Cloud Foundry to GCP are outdated. They may still work, but the document [in cf-deployment](https://github.com/cloudfoundry/cf-deployment/blob/master/gcp-deployment-guide.md) describes an easier way to deploy to GCP, and it's supported by the Infrastructure and RelInt teams. Would it make sense to replace the doc in this repo with a link to the one from cf-deployment?

**Comment by evandbrown** [comment]
Hey @dsabeti, the `cf-deployment` repo looks awesome. We bolted on a lot of docs back when the CPI started simply because they didn't exist anywhere else, and I'd love to start unbolting that stuff and letting it live where it makes sense. Would you say that `cf-deployment` is the official (to the extent that anything is official) way to do a deployment of CF to GCP?

@mrdavidlaing and @johnsonj are the other two folks who have contributed to the CF docs in the CPI. Are you fellas OK with the idea of linking out to the `cf-deployment` docs @dsabeti mentions?

**Comment by dsabeti** [comment]
Hey @evandbrown. It's definitely the _supported_ way to deploy to GCP and it works pretty well, but we're still advertising cf-deployment as not quite prod-ready. I'd say as long as you provide that caveat it should be fine.

**Comment by johnsonj** [comment]
fix with #252
