### ISSUE TITLE
bosh-user@ doesn't have enough permissions; but terraform@ does

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/bosh-google-cpi-release#211]
I'm going to describe this GCP issue as I saw it, but hopefully someone can think of something. Right now, I cannot create images nor VMs. When I `bosh2 upload-stemcell` I get the error:

```
23:47:05 | Error: CPI error 'Bosh::Clouds::CloudError' with message 'Creating stemcell: Creating Google Image from URL: Failed to create Google Image: googleapi: Error 403: Required 'compute.images.create' permission for 'projects/bosh-171403', forbidden' in 'create_stemcell' CPI method
```

But this was working a few days ago. I've been tearing down my GCP env (iam/network/vms) and rebuilding whilst writing new tutorial. All was happy. I had zookeeper cluster running. 

Then I uploaded the new windows2016 stemcell on a new BOSH; then attempted to upload the ubuntu stemcell and got the error above. 

But I can't deploy anything with the windows2016 stemcell as I get a different "Required 'compute...' permission" error. 
Ideas on debugging or resetting my environment?

But uploading the windows2016 stemcell continues to work:

```
23:54:18 | Update stemcell: Uploading stemcell bosh-google-kvm-windows2016-go_agent/1093.0.0-build.1 to the cloud (00:00:00)
23:54:18 | Update stemcell: Save stemcell bosh-google-kvm-windows2016-go_agent/1093.0.0-build.1 (https://www.googleapis.com/compute/v1/projects/cff-bosh-windows-stemcells/global/images/packer-1498657877) (00:00:00)
```

Why would one stemcell upload; but another one fail with permissions errors?

But more importantly; what might have happened to my GCP account? My IAM users seem to have lots of permissions.

When I reverted to deploying bosh with an IAM user with god/admin powers and it worked. Any ideas if GCP changed the required permissions for bosh-user@ service account to be able to create images/create vms?

**Comment by Everlag** [comment]
I'm in the process of rewriting the docs to use bosh2 and encountered exactly the same issue. Try renaming the user as a workaround, perhaps `bosh-director-deployment`.

**Comment by johnsonj** [comment]
Closing due to age. Re-open if this is still an issue.

**Comment by sachinyar** [comment]
I am facing the same issue, pls provide the fix for this:


Task 20 | 15:43:38 | Update stemcell: Extracting stemcell archive (00:00:00)
Task 20 | 15:43:38 | Update stemcell: Verifying stemcell manifest (00:00:00)
Task 20 | 15:43:39 | Update stemcell: Checking if this stemcell already exists (00:00:00)
Task 20 | 15:43:39 | Update stemcell: Uploading stemcell bosh-google-kvm-ubuntu-trusty-go_agent/3468.21 to the cloud (00:00:30)
                   L Error: CPI error 'Bosh::Clouds::CloudError' with message 'Creating stemcell: Creating Google Image from URL: Failed to create Google Image: Post https://www.googleapis.com/compute/...............: oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: dial tcp 74.125.28.84:443: i/o timeout' in 'create_stemcell' CPI method
Task 20 | 15:44:09 | Error: CPI error 'Bosh::Clouds::CloudError' with message 'Creating stemcell: Creating Google Image from URL: Failed to create Google Image: Post https://www.googleapis.com/compute/..................: oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: dial tcp 74.125.28.84:443: i/o timeout' in 'create_stemcell' CPI method

Task 20 Started  Fri Feb  9 15:43:38 UTC 2018
Task 20 Finished Fri Feb  9 15:44:09 UTC 2018
Task 20 Duration 00:00:31
Task 20 error


Uploading stemcell file:
  Expected task '20' to succeed but state is 'error'
Exit code 1
===== 2018-02-09 15:44:10 UTC Finished "/usr/local/bin/bosh --no-color --non-interactive --tty --environment=192.168.1.10 upload-stemcell /var/tempest/stemcells/light-bosh-stemcell-3468.21-google-kvm-ubuntu-trusty-go_agent.tgz"; Duration: 31s; Exit Status: 1
===== 2018-02-09 15:44:10 UTC Running "/usr/local/bin/bosh --no-color --non-interactive --tty --environment=192.168.1.10 upload-stemcell /var/tempest/stemcells/light-bosh-stemcell-3468.21-google-kvm-ubuntu-trusty-go_agent.tgz"
Using environment '192.168.1.10' as client 'ops_manager'

   0.00% 100.00% 259.69 KB/s 0s

-------------------------------

In json i am getting below message : 

{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "required",
    "message": "Login Required",
    "locationType": "header",
    "location": "Authorization"
   }
  ],
  "code": 401,
  "message": "Login Required"
 }
}
---------------------

I am unable to understand where I need to provide the user id/pwd?
pls help

**Comment by johnsonj** [comment]
@sachinyar - This looks like an unrelated issue. The first error you're receiving is a failure to fetch an oauth token from the Google Compute API. This could be two issues:
- Your deployment (PCF?) doesn't have internet access (eg: external IP is disabled and NAT is not properly configured). If you're using NAT ensure the proper routes are setup and your director/ops man have the proper network tags [[example route](https://github.com/cf-platform-eng/gcp-pcf-quickstart/blob/master/src/omg-tf/nat.tf#L32)]
- You hit a momentary timeout against the API service. Retry the deployment to see if that's the issue.

**Comment by pnatraj** [comment]
Thank you very much for pointing out the issue.

**Comment by sameerhashmi** [comment]
@sachinyar @pnatraj  how did you resolve this issue? I am getting the exact same thing while deploying PCF small footprint to GCP.

**Comment by pnatraj** [comment]
The best way of deploying the small foot print is through this, have you tried this ?

https://github.com/cf-platform-eng/gcp-pcf-quickstart/

**Comment by pnatraj** [comment]
There cold be multiple issues in the way the system is configured and one of it is the certificate configuration, In our case this was the certificate configuration.

**Comment by sameerhashmi** [comment]
I was actually doing the manual install. I can reconfigure the certificates or last option ill try the quickstart. Thanks!

**Comment by johnsonj** [comment]
This issue is an artifact that IAM propagation can take time and from my experience, deletion and recreation of the same service account makes it more prevalent.

The workaround is to use a unique name. The installer that @pnatraj linked generates a [unique service account name](https://github.com/cf-platform-eng/gcp-pcf-quickstart/blob/master/src/omg-tf/ops_manager.tf#L104) for each deployment to be sure that issue doesn't happen. If you're manually performing the steps at home and run into this issue then you can follow the same workaround.
